global:
  uid: 93266666-9320-7451-0239-66662fa66666      # 请务必修改此项目 默认 93266666-9320-7451-0239-66662fa66666
  url: https://ia.tinksp.cn:38031/upload         # 指示要求上传的后端处理地址 如 https://ia.liuzhen932.top/upload

locale:
  reload: '重载完成.'
  error: 'An error occurred unexpectedly.'
  failed-mkdir: ''                               # 改了也没用 这里没加载配置呢
  failed-save: 'Failed to save config!'          # 改了也没用 这里没加载配置呢
  failed-save-console: '未能成功保存配置文件'
  failed-read: '文件无法读取 (可能不存在)'
  failed-upload-console: '文件上传错误! 请将相关日志反馈给开发者'
  failed-upload-player: '文件上传失败! 请查看控制台并将相关日志反馈给开发者'
  success-upload: '文件上传成功! 输入 /iareload 重载'
  ready-upload: '文件分片完成, 开始上传...'